// src/components/sections/Divider.vue
<script setup lang="ts">
defineProps<{
    title: string;
}>();
</script>

<template>
    <div class="relative">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
            <div class="w-full border-t border-gray-200" />
        </div>
        <div class="relative flex justify-center text-sm font-medium leading-6">
            <span class="bg-white px-6 text-gray-900">{{ title }}</span>
        </div>
    </div>
</template>

// src/components/typography/Divider.tsx
interface Properties {
    text: string;
}

export const Divider = ({ text }: Properties) => {
    return (
        <div className="relative">
            <div className="absolute inset-0 flex items-center" aria-hidden="true">
                <div className="w-full border-t border-gray-200" />
            </div>
            <div className="relative flex justify-center text-sm font-medium leading-6">
                <span className="bg-white px-6 text-gray-900">{text}</span>
            </div>
        </div>
    );
};
